name: mini_news_intelligence
description: A Mini News Intelligence app built with Flutter, Riverpod and Hive.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  connectivity_plus: ^7.0.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^10.0.0
  timeago: ^3.2.2
  json_annotation: ^4.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0
  logger: ^2.6.2 

flutter:
  uses-material-design: true
